apiVersion: v1
kind: Secret
metadata:
  name: finances-env
  namespace: default
type: Opaque
stringData:
  .env: |
    # Plaid API Credentials
    PLAID_CLIENT_ID=6913b79ea16a42002270f8bc
    PLAID_SECRET=4ed7faa61211cf75bcf3376105ec67
    PLAID_ENV=development  # sandbox, development, or production
    PRODUCTION_PLAID_SECRET=4ed7faa61211cf75bcf3376105ec67
    
    # Plaid Access Token (generated after linking bank account)
    PLAID_ACCESS_TOKEN=access-production-a3dc18b9-453b-473b-b4f3-3e4a8ad4b514
    
    # Google Sheets Configuration
    GOOGLE_SHEET_ID=1YE1a0_q6e4pH0tiJtRSsYGy-1U-UN5WL6Q3CWNRT968
    GOOGLE_SERVICE_ACCOUNT_EMAIL="transaction-processor@financial-tracking-479419.iam.gserviceaccount.com"
    GOOGLE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDJqqLhYtJGtFBx\nJo0oYIfnH1838mQtwYey4ho/usowkoxavxBUyqP2oKqUQFVWuB/zSLyHZ0S4pLxj\nU4SWjH59q5yulTyjjDfFWGJEDSZ9J8yZDLjzq4Onv7ALf6RMao52D0ouTcp9UvSA\nM6PCXygZ7bqAZV25yjuVlUzYUGMONZNwjdPM7sOp/Skraglb2iQq3Imgv5J5IIgG\ngdrDEQ22n+bA9GIvvG/sE9bBXSaMLX1ls3n/S/6KbBJzp8erFhLZ0V2N+lJshcE+\n/IOxJqD9bR3vk+KRUvmORWEBhlIv6yLE6U1DREob3kCeUj+XTObayGpYGj41u6nH\neRc/XwR/AgMBAAECggEADmkGCIryMaEy2lMB5S+4plhEio/kfqyEkNC9RW6Igh4G\nr3lVpmlwe/ARIFTUhETV66F370j+zR7gY0yVfdh+NWas5IC/e4RKe+yL4Qb7iBfu\n88TH9ol79+Gnp7qwN9GpamA/Ub23SWtDE2IdQodgKzIkkIYtw1fjGBY6Dn74BQzI\nicfz0jXuHLPNiQd7x8OaYaca4t5zTuodzU6Gn7LM3sKLslJrf6bmwnPonf+FwIEg\nRkf8zmY5DCZaiuRpgb9hK+WH0GUl51X8vmOJGNan+UGfHaR7A9knhP4pjyuyB7+k\npUW2/SvLmnXmdMREXPFHw7bBpmplJ5SIt2hWZ+assQKBgQDmH6uyB+ZFmUfisnHJ\n6G3FYH2t9WsMS4ZSgoVdDgtizpj/D6VR5eMyRfpOOAotk8bwekm6oy1dzzNMkb/v\nQeWlg4n58LKrT2PQCGV05Yl/PJGEF8oXw3/kwWIBaNYQrAakt1i/q7X/+5NMl/BH\n49WEDSrlN+eUOwcp2OSfB7bIGQKBgQDgV8yPh5o2vxjBCt8qqhFz/KLxNYHHGeZD\nwp2KUpm56KkE1jOvlKoKrlFX45HaFSlWO0P3+PRKxrv83OD9hS8smPzJPf/cOPak\nfx3IT4kwaJg7ea0AhcQHLjXxezWvJoqLq117HweM9+wA1b7IdVSwbc/06G+xzEGT\nc2o5HrmkVwKBgHdtoFG4v80HC8OfEGbU9YMl3JPXdkLfP0q66jOtAkO5LLXSjN3A\nDPUeVBUcCEw3EVvkWzc9UGILEnh+e7nT3TbU2VqZjGBTx11DvkO4jG84I90F66AB\nmfJCWnaYzd/BJ4F8ldaDauT6zytE/zKQD1OE8eob5VeMet9A7QWLn1ShAoGAL52z\nB0vKyY/p2x9Jmq6aIbofg37N2sp+eydVdMRvaGwfY61rLvso1DeHgFYG4PjY2zqd\nBIbMowpnYBYpkuWvy5F1JemI4t8cSnHIinmHLsUkeosq0w+ROczvGiAClvhhM5/d\nqYI+ggclClBTvAxbO08zclHbUyt9R6SZiSIiWOUCgYBqDOsjosaxdaMFPflOg4Vl\nhntQNyGQcPkJj0zT1Knf6roZa4gSFu6HOTHLN7+X3s8JngNO4fwJkNreuebPKR7o\ncKWOLRVSna2sQEdGcF/+Q5EVx72Ih79J5XanLEEzFy0XcxuO6OAcyRcqasrxqpY6\nQwsTkEeKKWn83r3fFi09mg==\n-----END PRIVATE KEY-----\n"
    
    # Application Settings
    LOG_LEVEL=info  # debug, info, warn, error
    LOOKBACK_DAYS=7  # How many days to fetch transactions
    
    # Email Assignments
    USER_EMAIL_MITBURR=mitburr@gmail.com
    USER_EMAIL_RJKIRBY=rjkirby29@gmail.com
    USER_EMAIL_BILLS=bills@gmail.com
