#!/bin/bash
# Manual deployment guide - run these commands step by step

echo "=== Manual Deployment Steps ==="
echo ""
echo "1. Build image locally:"
echo "   docker build -t finances-categorizer:latest ."
echo ""
echo "2. Save and copy image:"
echo "   docker save finances-categorizer:latest -o /tmp/finances-categorizer.tar"
echo "   scp /tmp/finances-categorizer.tar em@192.168.1.2:/tmp/"
echo ""
echo "3. Load image on Sequoia (run on sequoia):"
echo "   ssh em@192.168.1.2"
echo "   sudo k3s ctr images import /tmp/finances-categorizer.tar"
echo ""
echo "4. Copy manifests to Sequoia:"
echo "   scp -r k8s em@192.168.1.2:~/transaction-processing/"
echo ""
echo "5. Apply manifests (run on sequoia):"
echo "   cd ~/transaction-processing"
echo "   sudo k3s kubectl apply -f k8s/apps/finances/secret.yaml"
echo "   sudo k3s kubectl apply -f k8s/apps/finances/deployment.yaml"
echo "   sudo k3s kubectl apply -f k8s/apps/finances/service.yaml"
echo "   sudo k3s kubectl apply -f k8s/ingress/finances-ingress.yaml"
echo ""
echo "6. Check deployment:"
echo "   sudo k3s kubectl get pods -l app=finances"
echo "   sudo k3s kubectl logs -l app=finances"
echo ""
echo "7. Access at: http://finances.grove"
